language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.4.20"
  - DJANGO="Django==1.6.11"
  - DJANGO="Django==1.7.7"

matrix:
  exclude:
    # Python 3.4 is not supported in Django before 1.7.
    - env: DJANGO="Django==1.4.20"
    - env: DJANGO="Django==1.6.11"
      python: 3.4

install:
  - pip install $DJANGO
  - pip install factory-boy
  - pip install coveralls
  - python setup.py develop

script:
  - cd example_project; coverage run manage.py test

after_success:
  - coveralls


