language: python

python:
  - 2.7
  - 3.3
  - 3.4

env:
  - DJANGO="Django==1.4.15"
  - DJANGO="Django==1.5.10"
  - DJANGO="Django==1.6.7"
  - DJANGO="Django==1.7"

matrix:
  exclude:
    # Python 3.4 is not supported in Django before 1.7.
    - env: DJANGO="Django==1.4.15"
    - env: DJANGO="Django==1.5.10"
    - env: DJANGO="Django==1.6.7"
      python: 3.4

install:
  - pip install $DJANGO
  - pip install factory-boy
  - python setup.py develop

script: cd example_project; python manage.py test

